#
# Blog Settings
#
author: Ugo Lattanzi
description: Ugo Lattanzi's tech world
url: http://imperugo.tostring.it
title: Ugo Lattanzi
subtitle: Web guy, MVP. Father. Snowboarder. All round nice guy.
gravatar_url: https://0.gravatar.com/avatar/91dc93f70aa2c457a41657437194933a
subscribe_rss: http://feeds.feedburner.com/imperugo
encoding: utf-8
highlighter: pygments
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Github repositories
github_user: imperugo
github_repo_url: https://github.com/imperugo/imperugo-it/

# Twitter
twitter_user: imperugo
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: it-tostring
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-8212043-1
google_analytics_domain: tostring.it

#
# Jekyll Settings
#
markdown: redcarpet
permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
