#
# Blog Settings
#
author: Ugo Lattanzi
description: Ugo Lattanzi's tech world
url: http://imperugoit.github.io
title: Ugo Lattanzi's tech world
subtitle: ...and more
gravatar_url: https://0.gravatar.com/avatar/91dc93f70aa2c457a41657437194933a
subscribe_rss: http://feeds.feedburner.com/imperugo

# Github repositories
github_user: imperugo
github_repo_url: https://github.com/imperugo/imperugo-it/

# Twitter
twitter_user: imperugo
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: imperugo
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-8212043-1



#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /blog/post/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories